import { run } from './runner.js';

await run([
  './ids.test.js',
  './clock.test.js',
  './order.test.js',
  './dates.test.js',
  './plural.test.js',
  './i18n.test.js',
  './canonical.test.js',
  './model.test.js',
  './selectors.test.js',
  './merge.test.js',
  './format.test.js',
  './sync.test.js',
  './status.test.js',
  './migration.test.js',
  './game.test.js',
  './planning-game.test.js',
  './reminders.test.js',
  './analytics.test.js',
  './treeDrop.test.js',
  './migration3.test.js',
  './retention.test.js',
  './media.test.js',
  './village.test.js',
  './villageWorld.test.js',
  './skills.test.js',
  './repeat.test.js',
  './query.test.js',
  './keys.test.js',
  './feast.test.js',
  './meals.test.js',
]);
